version: '2.3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/dockerbuild/ssl:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /root/dockerbuild/ssl:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw

  mysql_db_container:
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql

# clientes
  api_defreesa:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/backend/apiDefreesa:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=api-defreesa.defreesa.com
      - LETSENCRYPT_HOST=api-defreesa.defreesa.com
      - LETSENCRYPT_EMAIL=contacto@defreesa.com

  api_defreever:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/backend/apiDefreever:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=api-defreever.defreesa.com
      - LETSENCRYPT_HOST=api-defreever.defreesa.com
      - LETSENCRYPT_EMAIL=contacto@defreesa.com

  api_defreesa_partner:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/backend/apiDefreesaPartner:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=api-partner.defreesa.com
      - LETSENCRYPT_HOST=api-partner.defreesa.com
      - LETSENCRYPT_EMAIL=contacto@defreesa.com

  static_casasdrywall:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/html/casasdrywall:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=casasdrywall.com, www.casasdrywall.com
      - LETSENCRYPT_HOST=casasdrywall.com, www.casasdrywall.com
      - LETSENCRYPT_EMAIL=info@niomads.com

  static_defreesa:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/html/defreesa:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=defreesa.com,www.defreesa.com
      - LETSENCRYPT_HOST=defreesa.com,www.defreesa.com
      - LETSENCRYPT_EMAIL=info@defreesa.com

  static_tanatologia:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/html/tanatologiaperu:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=tanatologiaperu.com, www.tanatologiaperu.com
      - LETSENCRYPT_HOST=tanatologiaperu.com, www.tanatologiaperu.com
      - LETSENCRYPT_EMAIL=contacto@tanatologiaperu.com

  admin_defreesa:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/frontend/adminDefreesa:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=partner.defreesa.com
      - LETSENCRYPT_HOST=partner.defreesa.com
      - LETSENCRYPT_EMAIL=contacto@defreesa.com

  clientneumologiaperu:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
     - /root/Documents/html/frontendReservas:/usr/share/nginx/html:ro
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=neumologiayneumopediatria.com
      - LETSENCRYPT_HOST=neumologiayneumopediatria.com
      - LETSENCRYPT_EMAIL=contacto@neumologiayneumopediatria.com

  ecommerce_suap:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/frontend/suapProject:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=suap.pe, www.suap.pe
      - LETSENCRYPT_HOST=suap.pe, www.suap.pe
      - LETSENCRYPT_EMAIL=info@suap.pe

# niomads
  adminer_container:
    restart: always
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=admnr.niomads.com
      - LETSENCRYPT_HOST=admnr.niomads.com
      - LETSENCRYPT_EMAIL=info@niomads.com 

  static_mehgirlsclub:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/html/mehgirlsclub:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=mehgirlsclub.niomads.com
      - LETSENCRYPT_HOST=mehgirlsclub.niomads.com
      - LETSENCRYPT_EMAIL=info@niomads.com

  static_niomads:
    image: kimbtechnologies/php_smtp_nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/html/niomads:/php-code/:rw
    environment:
      - SMTP_SERVER=smtp.gmail.com # the mail server host
      - SMTP_PORT=587 # the port to deliver mails (587 for starttls or 465 for tls)
      - SMTP_USER=info@niomads.com # the username for the mail server
      - SMTP_PASS=122020Dzc! # the password for the mail server
      - VIRTUAL_HOST=niomads.com,www.niomads.com
      - LETSENCRYPT_HOST=niomads.com,www.niomads.com
      - LETSENCRYPT_EMAIL=info@niomads.com

  static_lacholapower:
    image: kimbtechnologies/php_smtp_nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/html/lacholapower:/php-code/:rw
    environment:
      - SMTP_SERVER=smtp.gmail.com # the mail server host
      - SMTP_PORT=587 # the port to deliver mails (587 for starttls or 465 for tls)
      - SMTP_USER=info@niomads.com # the username for the mail server
      - SMTP_PASS=122020Dzc! # the password for the mail server
      - VIRTUAL_HOST=lacholapower.niomads.com
      - LETSENCRYPT_HOST=lacholapower.niomads.com
      - LETSENCRYPT_EMAIL=info@niomads.com

# facturaprepago
  api_facturaprepago:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/backend/apiFacturaPrepago:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=api.facturaprepago.com
      - LETSENCRYPT_HOST=api.facturaprepago.com
      - LETSENCRYPT_EMAIL=contacto@facturaprepago.com

  admin_facturaprepago:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/frontend/adminFacturaPrepago:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=admin.facturaprepago.com
      - LETSENCRYPT_HOST=admin.facturaprepago.com
      - LETSENCRYPT_EMAIL=contacto@facturaprepago.com

  admin_elecciones:
    image: webdevops/php-nginx:7.4
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/frontend/webPanelElecciones:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - VIRTUAL_HOST=votaciones.facturaprepago.com
      - LETSENCRYPT_HOST=votaciones.facturaprepago.com
      - LETSENCRYPT_EMAIL=contacto@facturaprepago.com
  
  woocommerce_template:
    image: wordpress
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/ecommerce/woocommerce_template:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mysql_db_container
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=woocommerce_template
      - VIRTUAL_HOST=woocommerce.facturaprepago.com
      - LETSENCRYPT_HOST=woocommerce.facturaprepago.com
      - LETSENCRYPT_EMAIL=contacto@facturaprepago.com

  prestashop_template:
    image: prestashop/prestashop:1.7-7.0
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/ecommerce/prestashop_template:/var/www/html
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mysql_db_container
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop_template
      - PS_INSTALL_AUTO=0
      - VIRTUAL_HOST=prestashop.facturaprepago.com
      # - LETSENCRYPT_HOST=prestashop.facturaprepago.com
      # - LETSENCRYPT_EMAIL=contacto@facturaprepago.com

  static_facturaprepago:
    image: kimbtechnologies/php_smtp_nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - /root/Documents/html/facturaprepago:/php-code/:rw
    environment:
      - SMTP_SERVER=smtp.gmail.com # the mail server host
      - SMTP_PORT=587 # the port to deliver mails (587 for starttls or 465 for tls)
      - SMTP_USER=info@niomads.com # the username for the mail server
      - SMTP_PASS=122020Dzc! # the password for the mail server
      - VIRTUAL_HOST=facturaprepago.com, www.facturaprepago.com
      - LETSENCRYPT_HOST=facturaprepago.com, www.facturaprepago.com
      - LETSENCRYPT_EMAIL=contacto@facturaprepago.com

volumes:
    mysql_db_data_container:


